#!/usr/bin/env bash
# Usage: pswls example advanced fix-7
# Summary: Fixes Issue #7
# Help: Fixes Issue #7: https://github.com/37signals/pswls/issues/7

set -e

# Provide pswls completions
if [ "$1" = "--complete" ]; then  
	while [ ! "$1" == "" ]; do
	  if [ "$1" = "foo" ] || [ "$1" = "bar" ]; then
	    { echo baz; echo bla; } | sort | uniq
	  	exit
	  fi

	  shift
	done
  
	{ echo foo; echo bar; } | sort | uniq
	exit;
fi
