#!/usr/bin/env bash
# Usage: pswls example basic filecomplete
# Summary: Example of auto completion for files
# Help: This is an example of auto completion for files

# provide pswls completions
if [[ $1 == '--complete' ]]; then
    echo -l -h
    exit 0
fi
echo "ls"
